metadata:
    name: Street Spirit
    attribution: © OpenStreetMap contributors
    version: 0.0.1
    center: [0, 0, 4]
vector_layers:
    admin:
        description: Administrative boundaries
        sql:
          - minzoom: 4
            maxzoom: 14
            buffer: 16
            extent: 1024
            file: sql/admin.sql.jinja2
          - minzoom: 15
            maxzoom: 15
            buffer: 16
            extent: 4096
            file: sql/admin.sql.jinja2
    buildings:
        description: Building polygons
        sql:
          - minzoom: 13
            maxzoom: 14
            extent: 1024
            buffer: 2
            file: sql/buildings.sql.jinja2
          - minzoom: 15
            maxzoom: 15
            extent: 4096
            buffer: 8
            file: sql/buildings.sql.jinja2
    building-names:
        description: Building names
        sql:
          - minzoom: 15
            maxzoom: 15
            extent: 2048
            buffer: 8
            file: sql/building-names.sql.jinja2
    water:
        description: Ocean and water polygons
        sql:
          - minzoom: 4
            maxzoom: 14
            extent: 1024
            file: sql/water.sql.jinja2
          - minzoom: 15
            maxzoom: 15
            extent: 4096
            file: sql/water.sql.jinja2
    water-lines:
        description: Water linestrings
        fields:
            waterway: Type of waterway
            name: Name of waterway
        sql:
          - minzoom: 8
            maxzoom: 14
            extent: 1024
            buffer: 2
            file: sql/water-lines.sql.jinja2
          - minzoom: 15
            maxzoom: 15
            extent: 4096
            buffer: 8
            file: sql/water-lines.sql.jinja2
    roads:
        description: Linear road features
        fields:
            highway: Type of highway
        sql:
          - minzoom: 12
            maxzoom: 14
            extent: 1024
            buffer: 4
            file: sql/roads-high.sql.jinja2
          - minzoom: 15
            maxzoom: 15
            extent: 4096
            buffer: 16
            file: sql/roads-high.sql.jinja2
    transit-points:
        description: Transit-oriented points
        fields:
            station: If the point is a station or stop
            mode: Mode of transportation
        sql:
          - minzoom: 12
            maxzoom: 14
            extent: 512
            buffer: 0
            file: sql/transit-points.sql.jinja2
          - minzoom: 15
            maxzoom: 15
            extent: 2048
            buffer: 0
            file: sql/transit-points.sql.jinja2
    vegetation:
        description: vegetation areas
        fields:
            vegetation: Type of vegetation. One of wood, heath, scrub, wetland, or grass
            wetland: Wetland tag, if the object is a wetland
        sql:
          - minzoom: 10
            maxzoom: 14
            extent: 1024
            buffer: 4
            file: sql/vegetation.sql.jinja2
          - minzoom: 15
            maxzoom: 15
            extent: 4096
            buffer: 16
            file: sql/vegetation.sql.jinja2
